
labels:
  role: twsfrontend
  env: demo

deployment:
  name: twsfrontenddeployment
  replicas: 1
  strategy:
    maxSurge: 1
    maxUnavailable: 25%
  image:
    repository: twsfrontend
    tag: "1"
    pullPolicy: Never
  containerPort: 80

service:
  name: twsfrontend-service
  type: NodePort
  port: 80
  targetPort: 80
