apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: three-tier  
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30010

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: three-tier  
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: todo
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres1
          ports:
            - containerPort: 5432
